name: ba-enterprise-tools
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: owner/ba-enterprise-tools
  envs:
  - key: GEMINI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: FLASK_ENV
    scope: RUN_TIME
    value: production
  - key: FLASK_APP
    scope: RUN_TIME
    value: app.py
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: / 